default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  # --- General ---
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v4.2.0"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

  # --- Backend (Python) ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.7
    hooks:
      # Run the linter.
      - id: ruff-check
        types: [python]
        files: ^backend/
      # Run the formatter.
      - id: ruff-format
        types: [python]
        files: ^backend/

  # --- Frontend (TypeScript) ---
  - repo: local
    hooks:
      - id: prettier
        name: Run Prettier via pnpm
        entry: pnpm
        args: ["--dir=frontend/", "run", "pretty-hook"]
        language: node
        pass_filenames: false
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.30.1"
    hooks:
      - id: eslint
        files: ^frontend/
