default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  # --- General ---
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v4.2.0"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [
            "--verbose",
            "--force-scope",
            "--scopes=backend,frontend,ci,tooling,project",
          ]

  # --- Backend (Python) ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.7
    hooks:
      # Run the linter.
      - id: ruff-check
        types: [python]
        files: ^backend/
        stages: [pre-commit]

      # Run the formatter.
      - id: ruff-format
        types: [python]
        files: ^backend/
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: pytest
        name: Run pytest via uv
        entry: uv
        args: ["--directory=backend", "run", "pytest"]
        language: node
        files: python
        pass_filenames: false
        stages: [pre-commit]

      - id: pytest
        name: Run pyrefly via uv
        entry: uv
        args: ["--directory=backend", "run", "pyrefly"]
        language: node
        files: python
        pass_filenames: false
        stages: [pre-commit]

      # --- Frontend (TypeScript) ---
      - id: prettier
        name: Run Prettier via pnpm
        entry: pnpm
        args: ["--dir=frontend/", "run", "pretty-hook"]
        language: node
        pass_filenames: false
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.30.1"
    hooks:
      - id: eslint
        files: ^frontend/
        stages: [pre-commit]
